# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IAC_DIR: iac
      SRC_DIR: src
      DOTNET_VERSION: '6.0.x'
      CONFIGURATION: 'Release'
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET ${{ matrix.dotnet-version }}     
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet restore

    - name: Build
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      working-directory: ${{ env.SRC_DIR }}
      run: dotnet test --no-restore --no-build --verbosity normal
